spring.datasource.url=jdbc:mysql://mysql:3306/smart_freelance_subscription?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://eureka:8761/eureka

# Keycloak (JWT validation)
app.keycloak.issuer=https://localhost:8443/realms/smart-platform
app.keycloak.jwk-set-uri=http://host.docker.internal:8081/realms/smart-platform/protocol/openid-connect/certs

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
